### ISSUE TITLE
Cannot read properties of undefined (reading 'focus')

### ISSUE THREAD

**Issue by w4ugit** [react-tags/react-tags#977]
```
<ReactTags
  tags={tagsDesc}
  allowUnique={false}
  suggestions={suggestions}
  separators={delimiters}
  handleDelete={(i) => {
    setTagsDesc(tagsDesc.filter((tag, index) => index !== i));
  }}
  handleAddition={(tag) => {
    setTagsDesc([...tagsDesc, tag]);
  }}
  handleDrag={() => (tag, currPos, newPos) => {
    const newTags = tagsDesc.slice();

    newTags.splice(currPos, 1);
    newTags.splice(newPos, 0, tag);

    // re-render
    setTagsDesc(newTags);
  }}
  handleTagClick={() => {}}
  inputFieldPosition="bottom"
  autocomplete={false}
  classNames={{
    tags: "tagsClass",
    tagInput: "tagInputClass",
    tagInputField: "form-control",
    selected: "selectedClass",
    tag: "tagClass",
    remove: "removeClass",
    suggestions: "suggestionsClass",
    activeSuggestion: "activeSuggestionClass",
    editTagInput: "editTagInputClass",
    editTagInputField: "editTagInputField",
    clearAll: "clearAllClass",
  }}
  autoFocus={false}
/>
```

when i click delete i get an error

```
TypeError: Cannot read properties of undefined (reading 'focus')
    at updateAriaLiveStatus (ReactTags.tsx:196:1)
    at handleDelete (ReactTags.tsx:176:1)
    at onDelete (ReactTags.tsx:480:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
```

Drag and drop doesn't work either, but that's not a big deal

"react-tag-input": "^6.10.2",
"react-dnd": "^16.0.1",
"react-dnd-html5-backend": "^16.0.1",
"react-dom": "^18.2.0",

**Comment by heidenfuerst** [comment]
Same problem here. Did you manage to find a solution?

**Comment by ad1992** [comment]
Hey, which version are you using? This was fixed in `6.10.2`

**Comment by w4ugit** [comment]
"react-tag-input": "^6.10.2"

but the problem is still there. now everything stopped working at all (

**Comment by vingrad** [comment]
I confirm that the error is still exists in 6.10.2.

**Comment by ad1992** [comment]
Hi it works fine in the [example](https://codesandbox.io/p/sandbox/react-tags-l65545?file=%2Fsrc%2FApp.tsx), could you please share a reproducible codesandbox example so I can look into it?

**Comment by DaveTacker** [comment]
The problem seems to occur when using the `classNames` attribute, particurally, the `remove` class. [The library is looking for this class in particular](https://github.com/react-tags/react-tags/blob/feb69591240d4c2c22c8832535e877014071b195/src/components/ReactTags.tsx#L185C47-L185C58). Overwriting it by providing custom classNames causes an error. As a workaround, we can do this:

```text
classNames={{
  // ... other classes
  remove: 'ReactTags__remove ml-2 cursor-pointer text-red-500 hover:text-red-700', // added 'ReactTags__remove'
}}
```

**Comment by mhpaler** [comment]
nice catch @DaveTacker

**Comment by szaleq** [comment]
I'm facing the same issue when passing custom component to `removeComponent` prop. As @DaveTacker mentioned, adding `ReactTags__remove` class to my component solved the problem.   
  
BUT since this library allows to change class names or even pass custom component as a remove button, it should not rely on the class name. Instead it could pass a ref callback to these components and store HTMLElement instances as an array in another ref object instead of calling `querySelectorAll`.

**Comment by tadiotto** [comment]
[codesandbox example](https://codesandbox.io/p/sandbox/react-tags-forked-n6vhhp), if needed. Just remove any tag to reproduce the issue.
